var GLOBALPARAMS = {
  TITLE: "PING PONG ONLINE",
  VER: "0.1.SNAPSHOT",
  WIDTH: 800,
  HEIGHT: 600,
  BORDER_WIDTH: 10,
  BACKGROUND_COLOR: "#000000",
  PLAYER: {
    WIDTH: 20,
    HEIGHT: 80,
    GAP: 30,
  },
  BALL: {
    WIDTH: 15,
    HEIGHT: 15,
  },
  NET: {
    WIDTH: 6,
  },
  SCORE: {
    Y: 40,
    SIZE: 30,
    GAP: 50,
  },
  EDGE_SHOOT_ANGLE_ADJUST: 10,
  EDGE_ANGLE: 6,
  STRAIGHT_ADJUST: 7,
  STRATGHT_ANGLE: 7,
  SERVE_ANGLE: 30,
  GOAL: 10,
};
GLOBALPARAMS.CLIENT_GLOBALPARAMS = {
  TITLE: GLOBALPARAMS.TITLE,
  VER: GLOBALPARAMS.VER,
  WIDTH: GLOBALPARAMS.WIDTH,
  HEIGHT: GLOBALPARAMS.HEIGHT,
  BORDER_WIDTH: GLOBALPARAMS.BORDER_WIDTH,
  BACKGROUND_COLOR: GLOBALPARAMS.BACKGROUND_COLOR,
  NET: GLOBALPARAMS.NET,
};

module.exports = GLOBALPARAMS;
